[package]
name = "htmltable"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
clap-stdin = "0.6.0"
csv = "1.3.1"
serde = { version = "1.0.218", features = ["derive"] }
